### ISSUE TITLE
VMOS Pro (version 2.9.3)在哪里，2.9.2导入arm的zip文件失败

### ISSUE THREAD

**Issue by crazyn2** [VMOS-XiaoSuan/open-vmos-aosp_5.1#5]
VMOS Pro放出来的最新版本也就2.9.2，导入zip失败。但是小米商店最新的也就2.9.2，官网上的vmos pro还是2.0.0

**Comment by VMOS2021** [comment]
点击链接加入QQ频道【VMOS Pro安卓虚拟手机】：https://qun.qq.com/qqweb/qunpro/share?_wv=3&_wwv=128&appChannel=share&inviteCode=1XcR6XdZugk&from=181074&biz=ka&shareSource=5

刚跟同事确认了，群频道里面有 2.9.3，应用市场应该也快上了

**Comment by crazyn2** [comment]
好的，多谢，已解决
