### ISSUE TITLE
 Invalid LOCAL_SDK_VERSION 'current' Choices are: . 

### ISSUE THREAD

**Issue by dawnadvent** [VMOS-XiaoSuan/open-vmos-aosp_5.1#6]
build/core/java.mk:23: *** cts/common/device-side/device-setup: Invalid LOCAL_SDK_VERSION 'current' Choices are: .  Stop.

**Comment by VMOS2021** [comment]
应该是代码没有拉全的原因，可以在各个子模块中更新代码后再编译看看。
查找所有子模块
``` find |grep gitmodule```

然后cd到这些目录下面去更新子模块的代码
```
git submodule init
git submodule sync --recursive
git submodule update --init --recursive
```

**Comment by VMOS2021** [comment]
出现这个问题大概率是prebuilt下面的子模块没有拉全的问题，可以着重检查一下
