### ISSUE TITLE
麻烦问下你们是如何解除原生aosp的init需要root权限运行的限制

### ISSUE THREAD

**Issue by crazyn2** [VMOS-XiaoSuan/open-vmos-aosp_5.1#7]

**Comment by VMOS2021** [comment]
system/core/libcutils/fs_config.cpp 中可以配置文件的权限和用户属组

**Comment by crazyn2** [comment]
大佬，其实我想问的是非root下在adb shell执行init，原AOSP编译出来的init无法在adb shell非root下终端运行，没有日志输出，直接就退出了，但是在root shell 终端下是可以运行的，终端有输出，这就很奇怪，想把init弄成可以在非root adb shell终端下正常运行的，这样没有输出不好调试。root权限下运行init直接把手机弄成死机了
